### ISSUE TITLE
[support]: UnknownPackage netcdf

### ISSUE THREAD

**Issue by robertu94** [E4S-Project/e4s#104]
### Name of Software

e4s binary cache

### URL for Software

https://oaciss.uoregon.edu/e4s/inventory.html

### Contact Details

runderwood at anl.gov

### HPC System

Docker Container Ubuntu 20.04

### Request Description

We spoke briefly at SC22 regarding a bug I encountered using e4s that "netcdf" was an UnknownPackage.  I have since investigated further, and can confirm that there is no package in either my repo or spack.builtin which contains the text depends_on("netcdf​ or depends_on(​'netcdf`  by grepping for the matching string.

I then modified the spack source in lib/spack/spack/repo.py to print the exact spec that is getting matched rather than just its name.  The offending spec requested is `netcdf@4.7.1%gcc@7.3.0~dap~hdf4+mpi~parallel-netcdf+pic+shared maxdims=1024 maxvars
=8192 arch=linux-centos8-x86_64 ^hdf5@1.10.5%gcc@7.3.0~cxx~debug~fortran+hl+mpi+pic+shared~szip~threads
afe patches=b61e2f0 arch=linux-centos8-x86_64 ^libiconv@1.16%gcc@7.3.0 arch=linux-centos8-x86_64 ^libpc
iaccess@0.13.5%gcc@7.3.0 arch=linux-centos8-x86_64 ^libxml2@2.9.9%gcc@7.3.0~python arch=linux-centos8-x
86_64 ^mpich@3.2.1%gcc@7.3.0+hydra+pci+romio~slurm~verbs~wrapperrpath device=ch3 netmod=tcp pmi=pmi arc
h=linux-centos8-x86_64 ^xz@5.2.4%gcc@7.3.0 arch=linux-centos8-x86_64 ^zlib@1.2.11%gcc@7.3.0+optimize+pi
c+shared arch=linux-centos8-x86_64`

Which according to the e4s inventory exists: https://oaciss.uoregon.edu/e4s/packages/NETCDF.html

I then searched for this in the spack cache indicies .json files and the only entries I found for this package were the ones from e4s.  Removing these references as well as those to zeromq (also no longer in spack). as well as those  packages with namespace olcf finally enabled me to build my packages using the e4s binary mirror.

I would appreciate if you or someone from your team could investigate further and purge these packages and namespaces not distributed with upstream spack.

I've attached a Dockerfile that reproduces this issue.

### Relevant log output

```shell
root@a28489caffc1:/app# spack --debug install libpressio
==> [2022-11-23-11:05:28.663631] Imported install from built-in commands
==> [2022-11-23-11:05:28.664453] Reading config from file /app/etc/spack/defaults/config.yaml
==> [2022-11-23-11:05:28.673422] Skipping nonexistent config path /app/etc/spack/defaults/linux/config.yaml
==> [2022-11-23-11:05:28.673456] Skipping nonexistent config path /etc/spack/config.yaml
==> [2022-11-23-11:05:28.673475] Skipping nonexistent config path /etc/spack/linux/config.yaml
==> [2022-11-23-11:05:28.673492] Skipping nonexistent config path /app/etc/spack/config.yaml
==> [2022-11-23-11:05:28.673507] Skipping nonexistent config path /app/etc/spack/linux/config.yaml
==> [2022-11-23-11:05:28.673523] Skipping nonexistent config path /root/.spack/config.yaml
==> [2022-11-23-11:05:28.673538] Skipping nonexistent config path /root/.spack/linux/config.yaml
==> [2022-11-23-11:05:28.673806] Imported install from built-in commands
==> [2022-11-23-11:05:28.674180] Reading config from file /app/etc/spack/defaults/bootstrap.yaml
==> [2022-11-23-11:05:28.677256] Skipping nonexistent config path /app/etc/spack/defaults/linux/bootstrap.yaml
==> [2022-11-23-11:05:28.677288] Skipping nonexistent config path /etc/spack/bootstrap.yaml
==> [2022-11-23-11:05:28.677307] Skipping nonexistent config path /etc/spack/linux/bootstrap.yaml
==> [2022-11-23-11:05:28.677323] Skipping nonexistent config path /app/etc/spack/bootstrap.yaml
==> [2022-11-23-11:05:28.677339] Skipping nonexistent config path /app/etc/spack/linux/bootstrap.yaml
==> [2022-11-23-11:05:28.677360] Skipping nonexistent config path /root/.spack/bootstrap.yaml
==> [2022-11-23-11:05:28.677382] Skipping nonexistent config path /root/.spack/linux/bootstrap.yaml
==> [2022-11-23-11:05:28.680656] Reading config from file /app/etc/spack/defaults/repos.yaml
==> [2022-11-23-11:05:28.681430] Skipping nonexistent config path /app/etc/spack/defaults/linux/repos.yaml
==> [2022-11-23-11:05:28.681460] Skipping nonexistent config path /etc/spack/repos.yaml
==> [2022-11-23-11:05:28.681478] Skipping nonexistent config path /etc/spack/linux/repos.yaml
==> [2022-11-23-11:05:28.681494] Skipping nonexistent config path /app/etc/spack/repos.yaml
==> [2022-11-23-11:05:28.681514] Skipping nonexistent config path /app/etc/spack/linux/repos.yaml
==> [2022-11-23-11:05:28.681542] Reading config from file /root/.spack/repos.yaml
==> [2022-11-23-11:05:28.681937] Skipping nonexistent config path /root/.spack/linux/repos.yaml
==> [2022-11-23-11:05:28.683041] Skipping nonexistent config path /app/etc/spack/defaults/upstreams.yaml
==> [2022-11-23-11:05:28.683069] Skipping nonexistent config path /app/etc/spack/defaults/linux/upstreams.yaml
==> [2022-11-23-11:05:28.683091] Skipping nonexistent config path /etc/spack/upstreams.yaml
==> [2022-11-23-11:05:28.683106] Skipping nonexistent config path /etc/spack/linux/upstreams.yaml
==> [2022-11-23-11:05:28.683121] Skipping nonexistent config path /app/etc/spack/upstreams.yaml
==> [2022-11-23-11:05:28.683136] Skipping nonexistent config path /app/etc/spack/linux/upstreams.yaml
==> [2022-11-23-11:05:28.683151] Skipping nonexistent config path /root/.spack/upstreams.yaml
==> [2022-11-23-11:05:28.683165] Skipping nonexistent config path /root/.spack/linux/upstreams.yaml
==> [2022-11-23-11:05:28.683460] Reading config from file /app/etc/spack/defaults/config.yaml
==> [2022-11-23-11:05:28.692187] Skipping nonexistent config path /app/etc/spack/defaults/linux/config.yaml
==> [2022-11-23-11:05:28.692226] Skipping nonexistent config path /etc/spack/config.yaml
==> [2022-11-23-11:05:28.692247] Skipping nonexistent config path /etc/spack/linux/config.yaml
==> [2022-11-23-11:05:28.692266] Skipping nonexistent config path /app/etc/spack/config.yaml
==> [2022-11-23-11:05:28.692288] Skipping nonexistent config path /app/etc/spack/linux/config.yaml
==> [2022-11-23-11:05:28.692310] Skipping nonexistent config path /root/.spack/config.yaml
==> [2022-11-23-11:05:28.692331] Skipping nonexistent config path /root/.spack/linux/config.yaml
==> [2022-11-23-11:05:28.692384] DATABASE LOCK TIMEOUT: 3s
==> [2022-11-23-11:05:28.692401] PACKAGE LOCK TIMEOUT: No timeout
==> [2022-11-23-11:05:28.693291] Reading config from file /app/etc/spack/defaults/bootstrap.yaml
==> [2022-11-23-11:05:28.695978] Skipping nonexistent config path /app/etc/spack/defaults/linux/bootstrap.yaml
==> [2022-11-23-11:05:28.696009] Skipping nonexistent config path /etc/spack/bootstrap.yaml
==> [2022-11-23-11:05:28.696029] Skipping nonexistent config path /etc/spack/linux/bootstrap.yaml
==> [2022-11-23-11:05:28.696045] Skipping nonexistent config path /app/etc/spack/bootstrap.yaml
==> [2022-11-23-11:05:28.696063] Skipping nonexistent config path /app/etc/spack/linux/bootstrap.yaml
==> [2022-11-23-11:05:28.696086] Skipping nonexistent config path /root/.spack/bootstrap.yaml
==> [2022-11-23-11:05:28.696107] Skipping nonexistent config path /root/.spack/linux/bootstrap.yaml
==> [2022-11-23-11:05:28.696823] DATABASE LOCK TIMEOUT: 3s
==> [2022-11-23-11:05:28.696841] PACKAGE LOCK TIMEOUT: No timeout
==> [2022-11-23-11:05:28.696877] [BOOTSTRAP CONFIG SCOPE] name=_builtin
==> [2022-11-23-11:05:28.697675] [BOOTSTRAP CONFIG SCOPE] name=defaults, path=/app/etc/spack/defaults
==> [2022-11-23-11:05:28.697694] [BOOTSTRAP CONFIG SCOPE] name=defaults/linux, path=/app/etc/spack/defaults/linux
==> [2022-11-23-11:05:28.697712] [BOOTSTRAP CONFIG SCOPE] name=bootstrap, path=/root/.spack/bootstrap/config
==> [2022-11-23-11:05:28.697729] [BOOTSTRAP CONFIG SCOPE] name=bootstrap/linux, path=/root/.spack/bootstrap/config/linux
==> [2022-11-23-11:05:28.697878] Skipping nonexistent config path /app/etc/spack/defaults/compilers.yaml
==> [2022-11-23-11:05:28.697901] Skipping nonexistent config path /app/etc/spack/defaults/linux/compilers.yaml
==> [2022-11-23-11:05:28.697925] Skipping nonexistent config path /root/.spack/bootstrap/config/compilers.yaml
==> [2022-11-23-11:05:28.697971] Reading config from file /root/.spack/bootstrap/config/linux/compilers.yaml
==> [2022-11-23-11:05:28.711576] [BOOTSTRAP ROOT SPEC] clingo-bootstrap@spack+python %gcc target=x86_64
==> [2022-11-23-11:05:28.711608] [BOOTSTRAP MODULE clingo] Try importing from Python
==> [2022-11-23-11:05:28.711750] Reading config from file /app/etc/spack/defaults/bootstrap.yaml
==> [2022-11-23-11:05:28.714621] Skipping nonexistent config path /app/etc/spack/defaults/linux/bootstrap.yaml
==> [2022-11-23-11:05:28.714670] Skipping nonexistent config path /root/.spack/bootstrap/config/bootstrap.yaml
==> [2022-11-23-11:05:28.751943] Reading config from file /app/etc/spack/defaults/config.yaml
==> [2022-11-23-11:05:28.760582] Skipping nonexistent config path /app/etc/spack/defaults/linux/config.yaml
==> [2022-11-23-11:05:28.760625] Skipping nonexistent config path /root/.spack/bootstrap/config/config.yaml
==> [2022-11-23-11:05:28.825166] Reading config from file /app/etc/spack/defaults/packages.yaml
==> [2022-11-23-11:05:28.838399] Skipping nonexistent config path /app/etc/spack/defaults/linux/packages.yaml
==> [2022-11-23-11:05:28.838441] Skipping nonexistent config path /root/.spack/bootstrap/config/packages.yaml
==> [2022-11-23-11:05:28.838461] Skipping nonexistent config path /root/.spack/bootstrap/config/linux/packages.yaml
==> [2022-11-23-11:05:28.873536] [BOOTSTRAP MODULE clingo] The installed spec "clingo-bootstrap@spack+python %gcc target=x86_64 ^python@3.8/ba5ijauisd3uuixtmactc36vps7yfsrl" provides the "clingo" Python module
==> [2022-11-23-11:05:28.873790] Reading config from file /app/etc/spack/defaults/concretizer.yaml
==> [2022-11-23-11:05:28.875929] Skipping nonexistent config path /app/etc/spack/defaults/linux/concretizer.yaml
==> [2022-11-23-11:05:28.875962] Skipping nonexistent config path /etc/spack/concretizer.yaml
==> [2022-11-23-11:05:28.875981] Skipping nonexistent config path /etc/spack/linux/concretizer.yaml
==> [2022-11-23-11:05:28.875997] Skipping nonexistent config path /app/etc/spack/concretizer.yaml
==> [2022-11-23-11:05:28.876011] Skipping nonexistent config path /app/etc/spack/linux/concretizer.yaml
==> [2022-11-23-11:05:28.876026] Skipping nonexistent config path /root/.spack/concretizer.yaml
==> [2022-11-23-11:05:28.876040] Skipping nonexistent config path /root/.spack/linux/concretizer.yaml
==> [2022-11-23-11:05:28.876095] Reading config from file /app/etc/spack/defaults/repos.yaml
==> [2022-11-23-11:05:28.876888] Skipping nonexistent config path /app/etc/spack/defaults/linux/repos.yaml
==> [2022-11-23-11:05:28.876917] Skipping nonexistent config path /etc/spack/repos.yaml
==> [2022-11-23-11:05:28.876942] Skipping nonexistent config path /etc/spack/linux/repos.yaml
==> [2022-11-23-11:05:28.876964] Skipping nonexistent config path /app/etc/spack/repos.yaml
==> [2022-11-23-11:05:28.876986] Skipping nonexistent config path /app/etc/spack/linux/repos.yaml
==> [2022-11-23-11:05:28.877013] Reading config from file /root/.spack/repos.yaml
==> [2022-11-23-11:05:28.877402] Skipping nonexistent config path /root/.spack/linux/repos.yaml
==> [2022-11-23-11:05:28.901018] Reading config from file /app/etc/spack/defaults/config.yaml
==> [2022-11-23-11:05:28.909504] Skipping nonexistent config path /app/etc/spack/defaults/linux/config.yaml
==> [2022-11-23-11:05:28.909539] Skipping nonexistent config path /etc/spack/config.yaml
==> [2022-11-23-11:05:28.909557] Skipping nonexistent config path /etc/spack/linux/config.yaml
==> [2022-11-23-11:05:28.909572] Skipping nonexistent config path /app/etc/spack/config.yaml
==> [2022-11-23-11:05:28.909586] Skipping nonexistent config path /app/etc/spack/linux/config.yaml
==> [2022-11-23-11:05:28.909601] Skipping nonexistent config path /root/.spack/config.yaml
==> [2022-11-23-11:05:28.909615] Skipping nonexistent config path /root/.spack/linux/config.yaml
==> [2022-11-23-11:05:28.930415] Reading config from file /app/etc/spack/defaults/packages.yaml
==> [2022-11-23-11:05:28.943868] Skipping nonexistent config path /app/etc/spack/defaults/linux/packages.yaml
==> [2022-11-23-11:05:28.943906] Skipping nonexistent config path /etc/spack/packages.yaml
==> [2022-11-23-11:05:28.943925] Skipping nonexistent config path /etc/spack/linux/packages.yaml
==> [2022-11-23-11:05:28.943941] Skipping nonexistent config path /app/etc/spack/packages.yaml
==> [2022-11-23-11:05:28.943955] Skipping nonexistent config path /app/etc/spack/linux/packages.yaml
==> [2022-11-23-11:05:28.943970] Skipping nonexistent config path /root/.spack/packages.yaml
==> [2022-11-23-11:05:28.943984] Skipping nonexistent config path /root/.spack/linux/packages.yaml
==> [2022-11-23-11:05:28.945589] Reading config from file /app/etc/spack/defaults/mirrors.yaml
==> [2022-11-23-11:05:28.946156] Skipping nonexistent config path /app/etc/spack/defaults/linux/mirrors.yaml
==> [2022-11-23-11:05:28.946184] Skipping nonexistent config path /etc/spack/mirrors.yaml
==> [2022-11-23-11:05:28.946203] Skipping nonexistent config path /etc/spack/linux/mirrors.yaml
==> [2022-11-23-11:05:28.946218] Skipping nonexistent config path /app/etc/spack/mirrors.yaml
==> [2022-11-23-11:05:28.946233] Skipping nonexistent config path /app/etc/spack/linux/mirrors.yaml
==> [2022-11-23-11:05:28.946252] Reading config from file /root/.spack/mirrors.yaml
==> [2022-11-23-11:05:28.948626] Skipping nonexistent config path /root/.spack/linux/mirrors.yaml
==> [2022-11-23-11:05:28.948963] Checking existence of https://cache.e4s.io/build_cache/index.json
==> [2022-11-23-11:05:29.819905] Cached index for https://cache.e4s.io already up to date
==> [2022-11-23-11:05:29.820586] Checking existence of https://mirror.spack.io/build_cache/index.json
==> [2022-11-23-11:05:30.037778] Failure reading URL: Download failed: HTTP Error 404: Not Found
==> [2022-11-23-11:05:30.040313] DATABASE LOCK TIMEOUT: 3s
==> [2022-11-23-11:05:30.040418] PACKAGE LOCK TIMEOUT: No timeout
==> [2022-11-23-11:05:44.764705] Skipping nonexistent config path /app/etc/spack/defaults/compilers.yaml
==> [2022-11-23-11:05:44.764754] Skipping nonexistent config path /app/etc/spack/defaults/linux/compilers.yaml
==> [2022-11-23-11:05:44.764779] Skipping nonexistent config path /etc/spack/compilers.yaml
==> [2022-11-23-11:05:44.764799] Skipping nonexistent config path /etc/spack/linux/compilers.yaml
==> [2022-11-23-11:05:44.764821] Skipping nonexistent config path /app/etc/spack/compilers.yaml
==> [2022-11-23-11:05:44.764840] Skipping nonexistent config path /app/etc/spack/linux/compilers.yaml
==> [2022-11-23-11:05:44.764860] Skipping nonexistent config path /root/.spack/compilers.yaml
==> [2022-11-23-11:05:44.764887] Reading config from file /root/.spack/linux/compilers.yaml
==> [2022-11-23-11:05:58.698251] UnknownPackageError: Package 'netcdf@4.7.1%gcc@7.3.0~dap~hdf4+mpi~parallel-netcdf+pic+shared maxdims=1024 maxvars=8192 arch=linux-centos8-x86_64 ^hdf5@1.10.5%gcc@7.3.0~cxx~debug~fortran+hl+mpi+pic+shared~szip~threadsafe patches=b61e2f0 arch=linux-centos8-x86_64 ^libiconv@1.16%gcc@7.3.0 arch=linux-centos8-x86_64 ^libpciaccess@0.13.5%gcc@7.3.0 arch=linux-centos8-x86_64 ^libxml2@2.9.9%gcc@7.3.0~python arch=linux-centos8-x86_64 ^mpich@3.2.1%gcc@7.3.0+hydra+pci+romio~slurm~verbs~wrapperrpath device=ch3 netmod=tcp pmi=pmi arch=linux-centos8-x86_64 ^xz@5.2.4%gcc@7.3.0 arch=linux-centos8-x86_64 ^zlib@1.2.11%gcc@7.3.0+optimize+pic+shared arch=linux-centos8-x86_64' not found.
    You may need to run 'spack clean -m'.
==> [2022-11-23-11:05:58.698360] UnknownPackageError: Package 'netcdf@4.7.1%gcc@7.3.0~dap~hdf4+mpi~parallel-netcdf+pic+shared maxdims=1024 maxvars=8192 arch=linux-centos8-x86_64 ^hdf5@1.10.5%gcc@7.3.0~cxx~debug~fortran+hl+mpi+pic+shared~szip~threadsafe patches=b61e2f0 arch=linux-centos8-x86_64 ^libiconv@1.16%gcc@7.3.0 arch=linux-centos8-x86_64 ^libpciaccess@0.13.5%gcc@7.3.0 arch=linux-centos8-x86_64 ^libxml2@2.9.9%gcc@7.3.0~python arch=linux-centos8-x86_64 ^mpich@3.2.1%gcc@7.3.0+hydra+pci+romio~slurm~verbs~wrapperrpath device=ch3 netmod=tcp pmi=pmi arch=linux-centos8-x86_64 ^xz@5.2.4%gcc@7.3.0 arch=linux-centos8-x86_64 ^zlib@1.2.11%gcc@7.3.0+optimize+pic+shared arch=linux-centos8-x86_64' not found.
    You may need to run 'spack clean -m'.
==> [2022-11-23-11:05:58.698387] Error: Package 'netcdf@4.7.1%gcc@7.3.0~dap~hdf4+mpi~parallel-netcdf+pic+shared maxdims=1024 maxvars=8192 arch=linux-centos8-x86_64 ^hdf5@1.10.5%gcc@7.3.0~cxx~debug~fortran+hl+mpi+pic+shared~szip~threadsafe patches=b61e2f0 arch=linux-centos8-x86_64 ^libiconv@1.16%gcc@7.3.0 arch=linux-centos8-x86_64 ^libpciaccess@0.13.5%gcc@7.3.0 arch=linux-centos8-x86_64 ^libxml2@2.9.9%gcc@7.3.0~python arch=linux-centos8-x86_64 ^mpich@3.2.1%gcc@7.3.0+hydra+pci+romio~slurm~verbs~wrapperrpath device=ch3 netmod=tcp pmi=pmi arch=linux-centos8-x86_64 ^xz@5.2.4%gcc@7.3.0 arch=linux-centos8-x86_64 ^zlib@1.2.11%gcc@7.3.0+optimize+pic+shared arch=linux-centos8-x86_64' not found.
You may need to run 'spack clean -m'.
Traceback (most recent call last):
  File "/app/lib/spack/spack/repo.py", line 1232, in get_pkg_class
    module = importlib.import_module(fullname)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'spack.pkg.builtin.netcdf'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/lib/spack/spack/repo.py", line 1043, in get
    package_class = self.get_pkg_class(spec.name)
  File "/app/lib/spack/spack/repo.py", line 1234, in get_pkg_class
    raise UnknownPackageError(pkg_name)
spack.repo.UnknownPackageError: Package 'netcdf' not found.
    You may need to run 'spack clean -m'.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/lib/spack/spack/main.py", line 1000, in main
    return _main(argv)
  File "/app/lib/spack/spack/main.py", line 955, in _main
    return finish_parse_and_run(parser, cmd_name, env_format_error)
  File "/app/lib/spack/spack/main.py", line 983, in finish_parse_and_run
    return _invoke_command(command, parser, args, unknown)
  File "/app/lib/spack/spack/main.py", line 632, in _invoke_command
    return_val = command(parser, args)
  File "/app/lib/spack/spack/cmd/install.py", line 531, in install
    abstract_specs, concrete_specs = specs_from_cli(args, install_kwargs, reporter)
  File "/app/lib/spack/spack/cmd/install.py", line 447, in specs_from_cli
    concrete_specs = spack.cmd.parse_specs(
  File "/app/lib/spack/spack/cmd/__init__.py", line 227, in parse_specs
    spec.concretize(tests=tests)  # implies normalize
  File "/app/lib/spack/spack/spec.py", line 2978, in concretize
    self._new_concretize(tests)
  File "/app/lib/spack/spack/spec.py", line 2953, in _new_concretize
    result = solver.solve([self], tests=tests)
  File "/app/lib/spack/spack/solver/asp.py", line 2435, in solve
    result, _, _ = self.driver.solve(setup, specs, reuse=reusable_specs, output=output)
  File "/app/lib/spack/spack/solver/asp.py", line 625, in solve
    setup.setup(self, specs, reuse=reuse)
  File "/app/lib/spack/spack/solver/asp.py", line 1989, in setup
    self._facts_from_concrete_spec(reusable_spec, possible)
  File "/app/lib/spack/spack/solver/asp.py", line 1897, in _facts_from_concrete_spec
    self.impose(h, spec, body=True)
  File "/app/lib/spack/spack/solver/asp.py", line 1090, in impose
    imposed_constraints = self.spec_clauses(imposed_spec, body=body, required_from=name)
  File "/app/lib/spack/spack/solver/asp.py", line 1313, in spec_clauses
    clauses = self._spec_clauses(*args, **kwargs)
  File "/app/lib/spack/spack/solver/asp.py", line 1478, in _spec_clauses
    for virtual in dep.package.virtuals_provided:
  File "/app/lib/spack/spack/spec.py", line 1638, in package
    self._package = spack.repo.path.get(self)
  File "/app/lib/spack/spack/repo.py", line 849, in get
    return self.repo_for_pkg(spec).get(spec)
  File "/app/lib/spack/spack/repo.py", line 1045, in get
    raise UnknownPackageError(str(spec))
spack.repo.UnknownPackageError: Package 'netcdf@4.7.1%gcc@7.3.0~dap~hdf4+mpi~parallel-netcdf+pic+shared maxdims=1024 maxvars=8192 arch=linux-centos8-x86_64 ^hdf5@1.10.5%gcc@7.3.0~cxx~debug~fortran+hl+mpi+pic+shared~szip~threadsafe patches=b61e2f0 arch=linux-centos8-x86_64 ^libiconv@1.16%gcc@7.3.0 arch=linux-centos8-x86_64 ^libpciaccess@0.13.5%gcc@7.3.0 arch=linux-centos8-x86_64 ^libxml2@2.9.9%gcc@7.3.0~python arch=linux-centos8-x86_64 ^mpich@3.2.1%gcc@7.3.0+hydra+pci+romio~slurm~verbs~wrapperrpath device=ch3 netmod=tcp pmi=pmi arch=linux-centos8-x86_64 ^xz@5.2.4%gcc@7.3.0 arch=linux-centos8-x86_64 ^zlib@1.2.11%gcc@7.3.0+optimize+pic+shared arch=linux-centos8-x86_64' not found.
    You may need to run 'spack clean -m'.
```

### Reproduce Bug

```bash
Dockerfile


from ubuntu:20.04
RUN apt-get update -y && \
    DEBIAN_FRONTEND=noninteractive apt-get install -y software-properties-common build-essential ca-certificates coreutils curl environment-modules gfortran git gpg lsb-release python3 python3-distutils python3-venv unzip zip && \
    add-apt-repository -y ppa:ubuntu-toolchain-r/test && \
    apt-get update -y && \
    DEBIAN_FRONTEND=noninteractive apt-get install -y gcc-11 && \
    apt-get clean -y
RUN git clone -c feature.manyFiles=true --depth 1 https://github.com/spack/spack.git /app && \
    git clone --depth 1 https://github.com/robertu94/spack_packages /robertu94_packages && \
    source /app/share/spack/setup-env.sh && \
    spack compiler find && \
    spack repo add /robertu94_packages && \
    spack mirror add E4S https://cache.e4s.io && \
    spack buildcache keys -it



1. docker build -t e4sbug .
2. docker run -it --rm e4sbug
3. source /app/share/spack/setup-env.sh
4. spack install libpressio

I think any package with one or more virtual dependencies will also reproduce the bug, but this is the one that I used.

The bug can be resolved by editing the cache entry files to remove references to netcdf, zeromq and the namespace olcf as described above.
```

**Comment by sameershende** [comment]
@robertu94 I acknowledge this issue. We will investigate.

**Comment by eugeneswalker** [comment]
@robertu94 I believe this is a bug in Spack and have created an issue description here:
* https://github.com/spack/spack/issues/34108

The thing is, if `netcdf` isn't even a dependency of `libpressio`, then it seems to me Spack should not fail or even be affected by the presence of `netcdf` in the build cache. We have packages in our cache that come from custom package repos, which are needed for different workflows, and so I'm not sure the right solution can be "remove all of those." We also have packages that no longer exist in Spack period because we have been pushing binaries to the cache for a long time. 

In addition to our massive cache at `https://cache.e4s.io` which includes binaries going back over a year, we also create release-specific binary caches.
* `https://cache.e4s.io/22.11`
* `https://cache.e4s.io/22.08`
* etc...

These release-specific caches will only contain the package binaries generated as part of the associated E4S release process.

For instance, if you were to use `https://cache.e4s.io/22.11` as your build cache, you can install `libpressio` from cache without the same errors that you see in the massive, long-dated main cache. 

Here is what that would look like on:
* `Ubuntu 20.04`
* `spack@develop` checked out at `d56380fc` from `Wed Nov 23 12:39:45 2022 -0500`

```
$> spack mirror add E4S https://cache.e4s.io/22.11
$> spack buildcache keys -it
$> time spack install libpressio
...
==> Installing libpressio-0.88.0-jrusn25dlrtmym4h2mpgobchuykcgdak
==> Fetching https://cache.e4s.io/22.11/build_cache/linux-ubuntu20.04-x86_64-gcc-11.1.0-libpressio-0.88.0-jrusn25dlrtmym4h2mpgobchuykcgdak.spec.json.sig
gpg: Signature made Wed 09 Nov 2022 08:59:38 AM PST
gpg:                using RSA key 25645FA2B218FE55B4EF649E4345F04B40005581
gpg: Good signature from "University of Oregon - E4S" [ultimate]
==> Fetching https://cache.e4s.io/22.11/build_cache/linux-ubuntu20.04-x86_64/gcc-11.1.0/libpressio-0.88.0/linux-ubuntu20.04-x86_64-gcc-11.1.0-libpressio-0.88.0-jrusn25dlrtmym4h2mpgobchuykcgdak.spack
==> Extracting libpressio-0.88.0-jrusn25dlrtmym4h2mpgobchuykcgdak from binary cache
==> libpressio: Successfully installed libpressio-0.88.0-jrusn25dlrtmym4h2mpgobchuykcgdak
  Search: 0.00s.  Fetch: 2.65s.  Install: 1.25s.  Total: 3.90s
[+] /spack/opt/spack/linux-ubuntu20.04-x86_64/gcc-11.1.0/libpressio-0.88.0-jrusn25dlrtmym4h2mpgobchuykcgdak

real	2m56.525s
user	1m31.727s
sys	0m7.002s
```

**Comment by sameershende** [comment]
@robertu94 would you please confirm that using spack mirror add E4S https://cache.e4s.io/22.11 resolves the issue reported?

**Comment by robertu94** [comment]
@sameershende Thanks for following up.  I wanted to install my entire software stack using e4s just to make sure I didn't run into any secondary issues, and I ran that last night.  Everything ran as @eugeneswalker reported it should.  Thank you both for a quick turnaround near a holiday.

I am fine with either closing this issue, or waiting to close this until after https://github.com/spack/spack/issues/34108 is closed

**Comment by echus** [comment]
Hi @eugeneswalker, apologies for resurrecting this issue but I ran into a similar problem where I was getting `UnknownNamespaceError: Unknown namespace: olcf` when trying to install essentially any package using [https://cache.e4s.io/](https://cache.e4s.io/) with the latest spack. Using [https://cache.e4s.io/](https://cache.e4s.io/22.11) resolves my issue as well. Could I suggest keeping this open until https://github.com/spack/spack/issues/34108 is fixed so it is easy to find the workaround for others who run into the same bug?

**Comment by eugeneswalker** [comment]
> Could I suggest keeping this open until [spack/spack#34108](https://github.com/spack/spack/issues/34108) is fixed so it is easy to find the workaround for others who run into the same bug?

Reopening until we can resolve for `https://cache.e4s.io` specifically.

**Comment by tlivolsi** [comment]
> We raised this issue with the Spack developers and they understand the issue. Unfortunately, there is no quick fix at this point. The key problem is having `concretizer: reuse: true` when trying to use `https://cache.e4s.io` for binaries.
> 
> @echus can you try setting `concretizer: reuse: false` and see if that resolves the error?
> 
> ```
> spack config add concretizer:reuse:false
> ...
> ```

I had the same problem, and this worked for me.

**Comment by eugeneswalker** [comment]
Thanks to @tgamblin for the following PR which resolves this issue. Once merged, users will be able to take advantage of `concretizer:reuse:true` in conjunction with E4S build caches!
* https://github.com/spack/spack/pull/36990

**Comment by eugeneswalker** [comment]
Closing this issue for now as resolved.
