### ISSUE TITLE
[support]: spack load ncl results in an error about ninja being required

### ISSUE THREAD

**Issue by jscook2345** [E4S-Project/e4s#128]
### Name of Software

ncl

### Contact Details

jscook@lbl.gov

### HPC System

NERSC

### Request Description

When trying to load `ncl` in `e4s-22.11`, I get the following error about `ninja` missing, however it is there. It seems a dependency of `ncl` requires `ninja`, but it is not seeing it?

We do not specifically list `ninja` as an external in our configuration. Would that be the case?

There is a similar issue in the `spack` repo, which I will link here: https://github.com/spack/spack/issues/37704

Thanks again for your hard work and any help you can provide.

### Relevant log output

```shell
$ spack load ncl
==> Error: spack requires 'ninja'. Make sure it is in your path.
$ which ninja
/usr/bin/ninja
$ ninja --version
1.10.0
```

### Reproduce Bug

```bash
1. `module load e4s`
2. `spack env activate gcc`
3. `spack load ncl`
4. Error occurs here. `ncl` is not loaded
```

**Comment by jscook2345** [comment]
Here is some output from `spack --debug load ncl`

```console
==> [2023-06-09-14:59:05.674956] CommandNotFoundError: spack requires 'ninja'. Make sure it is in your path.
==> [2023-06-09-14:59:05.675008] Error: spack requires 'ninja'. Make sure it is in your path.
Traceback (most recent call last):
  File "/global/common/software/spackecp/perlmutter/e4s-22.11/83104/spack/lib/spack/spack/main.py", line 1003, in main
    return _main(argv)
  File "/global/common/software/spackecp/perlmutter/e4s-22.11/83104/spack/lib/spack/spack/main.py", line 958, in _main
    return finish_parse_and_run(parser, cmd_name, env_format_error)
  File "/global/common/software/spackecp/perlmutter/e4s-22.11/83104/spack/lib/spack/spack/main.py", line 986, in finish_parse_and_run
    return _invoke_command(command, parser, args, unknown)
  File "/global/common/software/spackecp/perlmutter/e4s-22.11/83104/spack/lib/spack/spack/main.py", line 635, in _invoke_command
    return_val = command(parser, args)
  File "/global/common/software/spackecp/perlmutter/e4s-22.11/83104/spack/lib/spack/spack/cmd/load.py", line 115, in load
    env_mod.extend(uenv.environment_modifications_for_spec(spec))
  File "/global/common/software/spackecp/perlmutter/e4s-22.11/83104/spack/lib/spack/spack/user_environment.py", line 92, in environment_modifications_for_spec
    spec, context="run", set_package_py_globals=set_package_py_globals
  File "/global/common/software/spackecp/perlmutter/e4s-22.11/83104/spack/lib/spack/spack/build_environment.py", line 1017, in modifications_from_dependencies
    add_modifications_for_dep(dspec)
  File "/global/common/software/spackecp/perlmutter/e4s-22.11/83104/spack/lib/spack/spack/build_environment.py", line 993, in add_modifications_for_dep
    dpkg.setup_dependent_package(changes, spec)
  File "/global/common/software/spackecp/perlmutter/e4s-22.11/83104/spack/var/spack/repos/builtin/packages/ninja/package.py", line 81, in setup_dependent_package
    determine_number_of_jobs(parallel=self.parallel),
  File "/global/common/software/spackecp/perlmutter/e4s-22.11/83104/spack/lib/spack/spack/util/path.py", line 160, in path_filter_caller
    return func(*args, **kwargs)
  File "/global/common/software/spackecp/perlmutter/e4s-22.11/83104/spack/lib/spack/spack/util/executable.py", line 315, in which_string
    raise CommandNotFoundError("spack requires '%s'. Make sure it is in your path." % args[0])
spack.util.executable.CommandNotFoundError: spack requires 'ninja'. Make sure it is in your path.
```

**Comment by sameershende** [comment]
I acknowledge this issue. We will investigate. Thanks.

**Comment by eugeneswalker** [comment]
> There is a similar issue in the `spack` repo, which I will link here: [spack/spack#37704](https://github.com/spack/spack/issues/37704)

Hi Justin, thanks for bringing this to our attention. Yes, we believe the issue you describe here is the same as https://github.com/spack/spack/issues/37704. We will coordinate with Spack team on a resolution and close the ticket here when it is resolved.

**Comment by eugeneswalker** [comment]
I confirmed with Spack team that unfortunately this bug remains unresolved. It has been added to a list of bugs to fix but is not complete yet. We will keep this issue open until we can report it has been resolved upstream.

**Comment by eugeneswalker** [comment]
A fix has been merged upstream! This is now resolved.
* https://github.com/spack/spack/pull/35737
